<?php

$content = '<div style="text-align:center;"><a target="_blank" href="http://opnoobs.com/" style="font-size:inherit">
<img id="xf6sw" style="max-width:500px" src="http://havgaming.com/EG/opnoobs.png">
</a>
<br>
<br>
<a target="_blank" href="http://www.blackmillgames.com/" style="font-size:inherit">
<img id="ccu4s" style="max-width:500px" src="http://havgaming.com/EG/blackmill2.png">
</a>
<br>
<br>
<a target="_blank" href="http://www.m2h.nl/" style="font-size:inherit">
<img id="g3vky" style="max-width:500px" src="http://havgaming.com/EG/M2H2.png">
</a>
</div>';