<?php

$content ='<center>
<a target="_blank" href="https://www.facebook.com/ethixgamingcommunity" style="font-size:inherit">
<img style="width:150px; height:150px" src="/styles/ethixgaming/theme/images/facebook.png">
</a>
</center>
<br>
<center>
<a target="_blank" href="https://twitter.com/EthixGaming" style="font-size:inherit">
<img style="width:150px; height:150px" src="/styles/ethixgaming/theme/images/twitter.png">
</a>
</center>';