<?php


$content = '<center>
<a target="_blank" href="http://www.teamspeak.com/invite/ts.ethixgaming.com" style="font-size:inherit">
<img style="width:190px; height:83px" src="http://files.iclanwebsites.com/ethixgaming/slideshow/ts3l.png">
</a>
<br />
<a target="_blank" href="http://www.teamspeak.com/invite/ts.ethixgaming.com" style="font-size:inherit">
<span style="font-size:15px; line-height:15px;">ts.ethixgaming.com</span>
</a><br />
<a target="_blank" href="http://www.tsviewer.com/index.php?page=ts_viewer&ID=1064840" style="font-size:inherit">
<img id="i6t7f" style="max-width:500px" src="http://www.tsviewer.com/promotion/dynamic_sig/sig.php/clan150x19_varig/1064840.png">
</a>
</center>';